#UsagiProspector should not be removed from Config file.
usagiprospector:
  - name: "Moloch Capture"
    search: "moloch-capture"
    path: "/data/moloch/bin/run_capture.sh"
    param: ""
  - name: "Moloch Viewer"
    search: "node-viewer"
    path: "/data/moloch/bin/run_viewer.sh"
    param: ""
