#UsagiProspector should not be removed from Config file.
usagiprospector:
  - name: "Redis"
    search: "redis-server"
    path: "/data/redis/bin/run_redis.sh"
    param: ""
  - name: "Moloch Viewer"
    search: "node-viewer"
    path: "/data/moloch/bin/run_viewer.sh"
    param: ""
